id: P44C1CCD4
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA30022
  instance_id: http://purl.bdrc.io/resource/IE30022
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ཕར་ཕྱིན།
  alt_title:
    zh-hans:
    - 内明学 · 波罗蜜多
  author: http://purl.bdrc.io/resource/P385
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    5aaaa5da75764a3fa81496613a396e1c:
      title: པོད ༡་ཕར་ཕྱིན།
      volume_number: 1
      base_file: UT30022_5754_0000.txt
      reference: http://purl.bdrc.io/resource/VL3E1E59C7168DB09E
      image_group: '5754'
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW30022
  - http://purl.bdrc.io/resource/W30022
  ocr_software: Namsel
created_at: '2021-12-22T11:18:07.356581'
last_modified_at: '2021-12-22T11:18:07.356589'
